#modificacion prueba
nombre = 'Carolina Quimbayo Gomez'
print('w' in nombre)
print('y' in nombre)
print()
print(len(nombre))
print()
print('Uso del metodo "upper":')
print(nombre.upper())
print(nombre.lower())
print('Uso del metodo "title":')
print(nombre.title())
print()
print('Uso del metodo "Count":')
print(nombre.count('e'))
print(nombre.count('o'))
